### ISSUE TITLE
create thumbnail errors 

### ISSUE THREAD

**Issue by breaklee** [hacksparrow/node-easyimage#73] opened 2015-08-16 14:54 UTC
version 2.1.0

install imageMagick
  => sudo port install ImageMagick

my error message is below

Command failed: convert ~/path/dff9f654782a35b5220dfd73dc011a78 -auto-orient -gravity Center -interpolate bicubic -strip -thumbnail 50x -crop 50x50+0+0 ~/path/dff9f654782a35b5220dfd73dc011a78.thumbnail
convert: image does not have a EXIF thumbnail `~/path/dff9f654782a35b5220dfd73dc011a78.thumbnail' @ error/thumbnail.c/WriteTHUMBNAILImage/185.

**Comment by hacksparrow** [comment] 2015-08-16 15:23
What's the imagemagick version? also is dff9f654782a35b5220dfd73dc011a78 a valid image?

**Comment by breaklee** [comment] 2015-08-17 06:22
@hacksparrow  yes.
'dff9f654782a35b5220dfd73dc011a78' name will be tmp name created by express.js(multer).

(ubuntu)not work:
ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
( using apt-get install )

(mac)not work:
ImageMagick 6.9.2-0 Q16 x86_64 2015-08-16 http://www.imagemagick.org

but there are something wrong.

1. i've changed file name to X.png.
2. 'convert ........' is not working.
3. 'sudo convert ......' is working.

**Comment by breaklee** [comment] 2015-08-17 06:43
i changed file name to dff9f654782a35b5220dfd73dc011a78.png
and dest file name also changed ~~.png
it works.

is it imageMagick bug?

**Comment by hacksparrow** [comment] 2015-08-17 09:14
@breaklee not sure, I will look into it.

**Comment by hacksparrow** [comment] 2015-08-19 17:27
@breaklee I confirmed with *ImageMagick 6.8.9-5 Q16 x86_64 2014-07-25* and *easyimage 2.1.0* to be working fine with extentionless file names on my Mac.

It might be a permission issue. If you think otherwise, it would be great if you can write a test to reproduce your scenario.

**Comment by nikita2106** [comment] 2016-07-29 08:06
facing the same issue , getting the error: Error: Command failed: convert C:\Users\Nikita\AppData\Local\Temp\upload_d4f65a44d81b157eaea7fefe2e5c4490 -auto-orient -gravity Center -interpolate bicubic -strip -thumbnail 256x -crop 256x256+0+0 public/uploads/579b0dd6032ea2140954e533_thumb.jpg
convert: unrecognized interpolate method `bicubic' @ error/convert.c/ConvertImageCommand/1907.

**Comment by guilherme22** [comment] 2016-10-05 18:01
same error: 
{ Error: Command failed: convert teste.png -auto-orient -gravity Center -interpolate bicubic -strip -thumbnail x70 -crop 70x70+0+0 ./dist/teste-thumbnail.png
convert: unrecognized interpolate method `bicubic' @ error/convert.c/ConvertImageCommand/1907.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'convert teste.png -auto-orient -gravity Center -interpolate bicubic -strip -thumbnail x70 -crop 70x70+0+0 ./dist/teste-thumbnail.png' }

**Comment by oksas** [comment] 2017-01-14 04:57
Getting the same error here too :(

PS thank you for all your work on this awesome package :D

**Comment by hacksparrow** [comment] 2017-01-14 20:13
@oksas can you share the imagemagick and OS details?

**Comment by oksas** [comment] 2017-01-19 20:36
Apologies for the slow reply. I'm on OSX El Capitan, and it looks like my imagemagick version is: `ImageMagick 7.0.4-3 Q16 x86_64 2017-01-11`

**Comment by luigi21** [comment] 2017-01-23 08:03
Hello oksas, 
I resolved the same problem on windows, i don't know if it's the same on OSX. 
My solution :
When you installing imageMagick, you need to check "Install legacy utilities (e.g. convert)" 
Hope it will helps

**Comment by oksas** [comment] 2017-01-24 21:25
@luigi21 Thank you for the fix, really appreciate you sharing! I will give it a shot :D

**Comment by MrEcl** [comment] 2017-02-27 09:27
I have the same error 

> convert: unrecognized interpolate method `bicubic' @ error/convert.c/ConvertImageCommand/1898.

Looks like 'bicubic'  is depreciated since IM v6.7.7-7:

>  Note that 'BiCubic' (interpolated Cubic Filter), refers to a very large family of filters, and as such is very inexact in its meaning. It is however still available, but its use is depreciated, in favor of more exact names.
> After IM v6.7.7-7 'BiCubic' is simply an alias to 'Catrom', which is typically regarded as a good 'cubic interpolator' (b=0, c=1/2). You should use the name 'Catrom' rather than 'BiCubic' so as to be clear what you are using for interpolation.

@hacksparrow may you change filter to 'catrom' for thumbnail method?

**Comment by mrkmg** [comment] 2018-01-10 19:52
This is fixed in release 2.2.0

**Closed by mrkmg** 2018-01-10 19:53 UTC
